repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
        exclude: REQUIREMENTS\.md$
    -   id: end-of-file-fixer
        exclude: REQUIREMENTS\.md$
    -   id: check-executables-have-shebangs
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: check-yaml
        files: .*\.(yaml|yml)$
    -   id: check-json
    -   id: pretty-format-json

# #65: support for git-secrets
-   repo: https://github.com/awslabs/git-secrets.git
    # We have to use an sha here instead of a tag because of awslabs/git-secrets#182
    rev: b9e96b3212fa06aea65964ff0d5cda84ce935f38
    hooks:
    -   id: git-secrets
