# 🏃‍♀️ Continuous Integration and Delivery: Unstable
# =================================================
#
# Note: for this workflow to succeed, the following secrets must be installed
# in the repository (or inherited from the repository's organization):
#
# ``ADMIN_GITHUB_TOKEN``
#     A personal access token of a user with collaborator or better access to
#     the project repository. You can generate this by visiting GitHub →
#     Settings → Developer settings → Personal access tokens → Generate new
#     token. Give the token scopes on ``repo``, ``write:packages``,
#     ``delete:packages``, ``workflow``, and ``read:gpg_key``.
# ``TEST_PYPI_USERNAME``
#     Username for test.pypi.org.
# ``TEST_PYPI_PASSWORD``
#     Password for ``TEST_PYPI_USERNAME``.
#


---

name: 🤪 Unstable integration & delivery


# Driving Event
# -------------
#
# What event starts this workflow: a push to ``main`` (or ``master`` in old
# parlance). For the "glob++" pattern syntax, see https://git.io/JJZQt

on:
    push:
        branches:
             - main
        paths-ignore:
            - 'CHANGELOG.md'
            - 'docs/requirements/**'
        workflow_dispatch:

concurrency: roundup


# What to Do
# ----------
#
# Round up, yee-haw!

jobs:
    unstable-assembly:
        name: 🧩 Unstable Assembly
        if: github.actor != 'pdsen-ci'
        runs-on: ubuntu-latest
        steps:
            -
                name: 💳 Checkout
                uses: actions/checkout@v3
                with:
                    lfs: true
                    token: ${{secrets.ADMIN_GITHUB_TOKEN}}
                    fetch-depth: 0
            -
                name: Build archive
                uses: a7ul/tar-action@v1.1.0
                id: compress
                with:
                    command: c
                    files: |
                        ./custom-datasets
                    outPath: custom-datasets.tar.gz
            -
                name: Upload binaries to release
                uses: svenstaro/upload-release-action@v2
                with:
                    repo_token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
                    file: custom-datasets.tar.gz
                    asset_name: reference dataset
                    tag: latest
                    overwrite: true
                    body: "Latest reference test dataset"
            -
                name: Install dependencies
                run: |
                    pip install sphinx sphinx_rtd_theme
            -
                name: Sphinx build
                run: |
                    sphinx-build doc _build
            -
                name: Deploy 🚀
                uses: JamesIves/github-pages-deploy-action@v4
                with:
                    folder: docs/build # The folder the action should deploy.



...

# -*- mode: yaml; indent: 4; fill-column: 120; coding: utf-8 -*-
